# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'hadeel-mahmoud'
      - run: git config --global user.email 'nez.hadeel@gmail.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      # Runs a single command using the runners shell
      - name: Before script
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      # Runs a set of commands using the runners shell
      - name: Publish
        run: |
          npm publish --access=public
          echo Published
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
